org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.problems.report=false
systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G
neogradle.subsystems.decompiler.enabled=false

mod_id=vanillainstincts
mod_name=Vanilla Instincts
mod_license=MIT
mod_version=1.0.0
mod_release_channel=stable
mod_release_date=2026-08-08
mod_group_id=fr.vanillainstincts
archives_name=vanilla-instincts
