name=${mod_name}
mod_id=${mod_id}
version=${mod_version}
release_channel=${mod_release_channel}
release_date=${mod_release_date}
minecraft_version=${target_minecraft_version}
loader=${target_loader}
loader_version=${target_loader_version}
java_version=${target_java_version}
license=${mod_license}
unit_tests=132
game_tests=${target_game_tests}
game_test_namespaces=${target_game_test_namespaces}
game_test_server_runs=${target_game_test_server_runs}
